server:
  port: 8083

spring:
  application:
    name: review-service
  datasource:
    url: jdbc:postgresql://localhost:5432/reviewdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: mySecretKeyForJWTTokenGeneration2024VeryLong

logging:
  level:
    com.moviereview: DEBUG